### ISSUE TITLE
Using username/password connection?

### ISSUE THREAD

**Issue by maxpaj** [OfficeDev/Office-Add-in-Auth0#2]
Hi,

thank you for providing an example of how to use Auth0 with Office addins! I have a question: How can I use this with Auth0's username/password connection?

Thanks in advance! :)

**Comment by Rick-Kirkham** [comment]
@maxpaj 
Could you clarify what you mean by the "username/password connection"?

**Comment by maxpaj** [comment]
@Rick-Kirkham without being too specific: 

Auth0 enables authentication through Social Connections (Facebook, Google, LinkedIn etc.) as well as plain old Username / password. The example you have provided only shows how to use Auth0 with Social Connections. Do you know how to make this work with the Username / password Auth0 connection?

**Comment by Rick-Kirkham** [comment]
@maxpaj 
Auth0 has changed their documentation quite a bit since this sample was created. Based on a very brief look at these three pages, I *think* you could extend the sample to handle the "plain old username / password" scenario. 

[Database Identity Providers](https://auth0.com/docs/connections/database)
[Authenticate Users with Username and Password](https://auth0.com/docs/connections/database/mysql)
[Authentication API](https://auth0.com/docs/api/authentication#introduction)

If you like you could request a new/expanded sample to show this scenario at  [Office User Voice](https://office.uservoice.com/forums/285186-general). If it gets enough votes, we'll implement it.

**Comment by maxpaj** [comment]
@Rick-Kirkham: Thanks!

I've been trying to get Auth0 authentication to work with my Outlook Addin, but the DialogAPI has not been working well for me... I use the Auth0 Lock widget in my popup dialog, which works, but when I try to post back data from the Dialog it's been giving an error:
`The target origin provided ('https://outlook.office.com') does not match the recipient window's origin (<my url>).`

I'm not seeing this error in the desktop version of Outlook, only in Outlook web. Have you seen this error before?

EDIT: Found a solution. A breaking change in the Dialog API broke my code.
